Repository AICoE/prometheus-anomaly-detector, pull requests merged in 2019-10, with the labels that each got.

#73 Update oc-image-build-template.yaml
  openshift/oc-image-build-template.yaml
Labels: approved, size/L

#76 Added kebechet support
  .thoth.yaml
Labels: approved, size/S

#78 Fix environment.yml format
  environment.yml
Labels: size/M

#77 Run training and tornado server in different processes
  Pipfile
  app.py
  environment.yml
  requirements.txt
Labels: approved, size/L, size/M

#80 fixed tabbing in ocp dc template
  openshift/oc-deployment-template.yaml
Labels: approved, do-not-merge/needs-rebase, size/L
