Repository AICoE/prometheus-anomaly-detector, pull requests merged in 2019-11, with the labels that each got.

#82 Update oc-buildconfig to use the thoth reccomendation container image
  .thoth.yaml
  Pipfile.lock
  openshift/oc-image-build-template.yaml
Labels: approved, size/M, size/XL

#83 Sync master changes with the fourier model branch
  .thoth.yaml
  Pipfile.lock
  openshift/oc-image-build-template.yaml
Labels: size/XL

#86 Add the SARIMA notebook
  notebooks/prometheus_anomaly_detection_sarima_test.ipynb
Labels: approved, size/L

#87 Modify the SARIMA notebook
  notebooks/prometheus_anomaly_detection_sarima_test.ipynb
Labels: approved, size/L
