Repository AICoE/prometheus-anomaly-detector, pull requests merged in 2021-07, with the labels that each got.

#147 adding a new env variable that provides an option between sequential …
  app.py
  configuration.py
Labels: lgtm, size/M

#150 Add k8s manifests
  openshift/k8s-deployment.yaml
  openshift/k8s-service.yaml
  openshift/k8s-servicemonitor.yaml
Labels: size/M

#152 Update dependencies
  Dockerfile
  Pipfile
  Pipfile.lock
  environment.yml
  model.py
  model_lstm.py
  requirements.txt
  set_uid.sh
Labels: size/XXL

#154 Update Dockerfile to use ubi8 python38 base image instead of miniconda
  Dockerfile
Labels: size/S

#156 adding a description for the FLT_PARALLELISM option in the README file
  README.md
Labels: lgtm, size/XS

#158 Set tensorflow less than 2.5 to fix pipfile lock error with tf 2.5
  Pipfile
  Pipfile.lock
  environment.yml
  requirements.txt
Labels: lgtm, size/XL
